IMPORTING NUMPY

In [10]:
import numpy as np

In [58]:
import pandas as pd

In [11]:
numpy.array([1,2,3])

array([1, 2, 3])

In [12]:
numpy.array([1,2,3,4,5,6,7])

array([1, 2, 3, 4, 5, 6, 7])

CREATING ARRAYS

In [13]:
a=numpy.array([1,2,3,4])

In [14]:
a

array([1, 2, 3, 4])

In [15]:
a.size

4

CREATING ARRAYS IN COLUMN FORMS

In [16]:
p=np.array([[1,2],[3,4]])

In [17]:
p

array([[1, 2],
       [3, 4]])

In [18]:
np.array([[10,20],[30,40]])

array([[10, 20],
       [30, 40]])

In [19]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [22]:
j=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
j

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
j.shape

(3, 3)

In [25]:
j.itemsize

4

In [68]:
j=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [69]:
j

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

RESHAPING ARRAYS 

In [33]:
np.arange(14).reshape(7,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

GENERATING RANDOM ARRAYS

In [41]:
g=np.random.random([2,3])

In [42]:
g

array([[0.6366038 , 0.18854521, 0.96425226],
       [0.39558325, 0.96772092, 0.70585972]])

GENERATING ARRAYS OF 1s

In [37]:
f=np.ones([2,3])

In [38]:
f

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
y=g+f

In [44]:
y

array([[1.6366038 , 1.18854521, 1.96425226],
       [1.39558325, 1.96772092, 1.70585972]])

In [45]:
t=np.array([12,13,14,15,16,17,18,19,20])

In [46]:
t

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

SLICING ARRAYS FROM WHERE IT SHOULD START AND END

SHOWING LAST 5 DATA

In [48]:
t[-5:]

array([16, 17, 18, 19, 20])

SHOWING LAST 5 MINUS LAST NUMBER

In [52]:
t[-6:-1]

array([15, 16, 17, 18, 19])

In [54]:
g=np.arange(20)

In [55]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

STARTING FROM A PARTICULAR NUMBER

In [57]:
g[6:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

CREATING SERIES WITH PANDAS

In [60]:
a=pd.Series([54,34,12,77,67], index=[1,2,3,4,5])

In [61]:
a

1    54
2    34
3    12
4    77
5    67
dtype: int64

In [62]:
y=pd.Series([2.4,4.7,1.4,6.6,7.8], index=[10,20,30,40,50])

In [63]:
y

10    2.4
20    4.7
30    1.4
40    6.6
50    7.8
dtype: float64

In [64]:
y[20]

4.7

In [66]:
y[0:2]

10    2.4
20    4.7
dtype: float64

CONVERTING A NUMPY ARRAY INTO PANDAS SERIES

In [70]:
pd.Series(j)

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
dtype: int32

CREATING DICTIONARY

In [72]:
dict1={'sno':101, 'Name': 'ABC'}

In [73]:
dict1

{'sno': 101, 'Name': 'ABC'}

In [74]:
pd.Series(dict1)

sno     101
Name    ABC
dtype: object

DATAFRAME

In [75]:
pd.DataFrame(data=[1,2,3,4])

0
0  1
1  2
2  3
3  4

In [82]:
b=[['Hammed',29],['Balikis',29],['Soliu',24]]

In [83]:
b

[['Hammed', 29], ['Balikis', 29], ['Soliu', 24]]

In [84]:
pd.DataFrame(data=b)

0   1
0   Hammed  29
1  Balikis  29
2    Soliu  24

In [85]:
h=[['Mariam',27],['Balikis',29],['Hammed',29],['Habeeb',27],['Soliu',24]]

In [86]:
h

[['Mariam', 27],
 ['Balikis', 29],
 ['Hammed', 29],
 ['Habeeb', 27],
 ['Soliu', 24]]

In [87]:
pd.DataFrame(data=h)

0   1
0   Mariam  27
1  Balikis  29
2   Hammed  29
3   Habeeb  27
4    Soliu  24

In [90]:
pd.DataFrame(data=h,columns=['Name','Age'],index=[10,20,30,40,50])

Name  Age
10   Mariam   27
20  Balikis   29
30   Hammed   29
40   Habeeb   27
50    Soliu   24

CONVERTING A DICTIONARY TO A DATAFRAME

In [92]:
dict2={'sno':[1,2,3],'Name':['Hammed','Balikis','Habeeb'],'Age':[29,29,27]}

In [93]:
dict2

{'sno': [1, 2, 3],
 'Name': ['Hammed', 'Balikis', 'Habeeb'],
 'Age': [29, 29, 27]}

In [94]:
pd.DataFrame(data=dict2)

sno     Name  Age
0    1   Hammed   29
1    2  Balikis   29
2    3   Habeeb   27